language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        coverity_scan:
          project:
            name: "leo-yuriev/libmdbx"
            version: 0.1
            description: "Build submitted via Travis CI"
          notification_email: leo@yuriev.ru
          build_command_prepend: "make clean"
          build_command: "make all -j 4"
          branch_pattern: coverity_scan
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - libgtest-dev
#            - valgrind
#            - clang-format-3.8
      env:
        - TOOLCHAIN_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake
            - libgtest-dev
      env:
        - TOOLCHAIN_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - libgtest-dev
      env:
        - TOOLCHAIN_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libstdc++-5-dev
            - cmake
            - libgtest-dev
      env:
        - TOOLCHAIN_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - libstdc++-5-dev
            - cmake
            - libgtest-dev
      env:
        - TOOLCHAIN_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

# GCC-8 BROKEN FOR NOW: /usr/lib/gcc/x86_64-linux-gnu/8/include/immintrin.h:113:10: fatal error: movdirintrin.h: No such file or directory
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-8
#            - cmake
#            - libgtest-dev
#      env:
#        - TOOLCHAIN_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  - eval "${TOOLCHAIN_EVAL}"


before_script: >
  if [ "${TRAVIS_BRANCH}" = "coverity_scan" ]; then
    # implement Coverity Scan with before_script instead of addons.coverity_scan
    if grep -q '[0-9]\+\.1$' <<< "${TRAVIS_JOB_NUMBER}"; then
      export COVERITY_SCAN_BRANCH=1
      echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      curl -s 'https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh' | COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG" COVERITY_SCAN_NOTIFICATION_EMAIL="leo@yuriev.ru" COVERITY_SCAN_BUILD_COMMAND="make -j4" COVERITY_SCAN_BUILD_COMMAND_PREPEND="make clean" COVERITY_SCAN_BRANCH_PATTERN="$TRAVIS_BRANCH" bash || cat cov-int/scm_log.txt
    else
      echo "Skip CoverityScan for unrelated os/compiler"
    fi
  fi

script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make all check; fi
